#!/usr/bin/env bash
#
# Build files list and check firmware.

files=$(git diff --cached --name-only --diff-filter=ACM |
  grep -E '^firmware/.*\.[ch]$')

[ -z "$files" ] || clang-format --dry-run -Werror $files
