class Type: ...

class Object:
    def GetType(self) -> Type: ...

class ValueType(Object): ...

class Enum(ValueType):
    def __int__(self) -> int: ...
    @staticmethod
    def ToObject(
        enumType: Type,
        value: int,
    ) -> Object: ...

class Decimal(ValueType): ...

class Convert:
    @staticmethod
    def ToDecimal(value: float) -> Decimal: ...
