/**
 * @file path.h
 * @brief Generates a special path that the beam profiler follows.
 *
 * The purpose of this module is the generation of a "modified raster", which is
 * the path that the beam profiler moves along in the x-y plane. This path is
 * designed to minimize the amount of travel and time taken while profiling all
 * points on the given grid.
 *
 * The modified raster is a raster scan that starts and ends on one point: the
 * origin or the point closest to it (referred to as the "anchor"). It enables
 * alternation between a horizontal and vertical raster for grids where both
 * dimensions are even or odd. One diagonal movement is used for odd grids, as
 * it takes the same amount of time and a Hamiltonian cycle is not possible.
 *
 * The modified raster also handles edge cases (e.g. grids of insufficient size,
 * axes that do not contain the origin, etc.), minimizes the movement of the
 * stages for each grid, and balances continuous movement between the stages.
 *
 * Positions are generated incrementally as the path is traversed so that memory
 * requirements do not increase with path size.
 */
#ifndef APP_PATH_H
#define APP_PATH_H

#include <stdbool.h>
#include <limits.h>

#define PATH_COORD_MIN (INT_MIN / 2)
#define PATH_COORD_MAX (INT_MAX / 2)

/** @brief Path status codes. */
typedef enum
{
    PATH_STATUS_OK = 0,
    PATH_STATUS_ERR_BOUNDS_MIN_GREATER_THAN_MAX,
    PATH_STATUS_ERR_BOUNDS_TOO_LARGE,
} path_status_t;

/**
 * @brief For storage of the direction of the raster.
 *
 * The raster direction is parallel to the axis along which most travel occurs.
 * A horizontal raster resembles the letter Z and a vertical raster resembles
 * the letter N.
 *
 * NOTE: This is important in the actual geometry of the path as well as the
 *       balancing of continuous work between the two stages.
 */
typedef enum
{
    PATH_RASTER_DIRECTION_HORIZONTAL = 0,
    PATH_RASTER_DIRECTION_VERTICAL,
} path_raster_direction_t;

/** @brief Traversal phase. */
typedef enum
{
    PATH_PHASE_READY = 0,
    PATH_PHASE_ONGOING,
    PATH_PHASE_RETURNING,
    PATH_PHASE_DONE,
} path_phase_t;

/** @brief Define a position with x and y coordinates. */
typedef struct
{
    int x; /**< The x-coordinate in units. */
    int y; /**< The y-coordinate in units. */
} path_coords_t;

/** @brief Define a local position with row and column indices. */
typedef struct
{
    int row; /**< The row index. */
    int col; /**< The column index. */
} path_indices_t;

/**
 * @brief Structure for path state.
 *
 * The raster is generated in a local space where indices (counting from zero
 * upward) function as coordinates. The raster is then mapped to the actual
 * coordinate system.
 *
 * In the local space, the raster is generated horizontally, so vertical rasters
 * are generated by transposing from the local space. Thus, for even grids, the
 * orientation of the raster in the local space is chosen such that the number
 * of rows is even.
 */
typedef struct
{
    bool                    corners_only;     /**< Only corner generation. */
    path_raster_direction_t raster_direction; /**< Current raster direction. */

    path_phase_t   phase;   /**< Current traversal phase. */
    path_indices_t current; /**< Local indices of the current position. */

    path_coords_t  zero;   /**< Coordinates of local minimum indices. */
    path_indices_t anchor; /**< Local indices of the anchor. */

    int num_rows; /**< Local number of rows. */
    int num_cols; /**< Local number of columns. */
} path_t;

/** @brief Initialize a path. */
path_status_t path_init(path_t                  *path,
                        bool                     corners_only,
                        path_raster_direction_t *prev_raster_direction,
                        int                      x_min,
                        int                      x_max,
                        int                      y_min,
                        int                      y_max);

/**
 * @brief Get the next position in the path.
 *
 * Computes the next position and updates the state of the path.
 *
 * NOTE: The last point in the path returned by this function is the anchor,
 *       even though capture ends at the point before the anchor (unless there
 *       is only one point). This ensures the detector starts and ends at the
 *       same point, eliminating unnecessary movement latency during the next
 *       profile should the grid remain the same.
 */
path_coords_t path_next_coords(path_t *path);

/** @brief Get the path generation phase. */
path_phase_t path_get_phase(path_t const *path);

#endif
